[tool.black]
line-length = 80
target-version = ['py35']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
  )/
  | donkeycar/parts/keras.py
)
'''
